rootProject.name = "dry-framework"

include("dry-application")
include("dry-common")
include("dry-common-jackson")
include("dry-configuration")
include("dry-data")
include("dry-data-sql")
include("dry-dependency")
include("dry-http")
include("dry-http-client")
include("dry-http-server")
include("dry-http-server-javelin")
include("dry-jwt")
include("dry-jwt-auth0")
include("dry-objectstore")
include("dry-qrcode")
include("dry-security")
include("dry-validation")
